AnonPolls/urls.py
from django.contrib import admin
from django.urls import path, include
from polls.views import IndexView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('polls/', include('polls.urls', namespace='polls')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from polls.utils import user_is_author
from polls.views import (PollsListView, CreateSurveyView, SurveyResponseView,
                         delete_survey, SurveyDetailView, EditSurveyView, thank_you,
                         survey_statistics, PollsPrivateListView, DownloadSurveyExcelView,
                         DownloadSurveyPDFView, DownloadFileView)
from django.conf.urls.static import static
from django.conf import settings

app_name = 'polls'
#

urlpatterns = [
    path('', PollsListView.as_view(), name='index'),
    path('private/', login_required(PollsPrivateListView.as_view()), name='private'),
    path('create/', login_required(CreateSurveyView.as_view()), name='create_survey'),
    path('detail/<slug:survey_slug>/', SurveyDetailView.as_view(), name='survey_detail'),
    path('edit/<slug:survey_slug>/', user_is_author(EditSurveyView.as_view()), name='edit_survey'),
    path('delete/<slug:survey_slug>/', user_is_author(delete_survey), name='delete_survey'),
    path('response/<slug:survey_slug>/', SurveyResponseView.as_view(), name='respond_to_survey'),
    path('<slug:survey_slug>/statistics/', user_is_author(survey_statistics), name='survey_statistics'),
    path('<slug:survey_slug>/statistics//', user_is_author(DownloadSurveyPDFView.as_view()),
         name='download_survey_pdf'),
    path('<slug:survey_slug>/statistics///', user_is_author(DownloadSurveyExcelView.as_view()),
         name='download_survey_excel'),
    path('download/<str:filename>/', DownloadFileView.as_view(), name='download_file'),
    path('thank/', thank_you, name='thank_you'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import (UserLoginView,
                         UserLogoutView)
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', login_required(UserLogoutView.as_view()), name='logout'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/models.py
import uuid

from unidecode import unidecode
from django.db import models
from django.utils.text import slugify

from AnonPolls import settings


class Survey(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, blank=True, null=True, max_length=255)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    show_author = models.BooleanField(default=False)
    survey_visibility = models.CharField(max_length=10, choices=[('public', 'Public'), ('private', 'Private')])
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            # Перетворюємо заголовок в ASCII, використовуючи unidecode
            title_transliterated = unidecode(self.title)
            # Створюємо slug
            self.slug = slugify(title_transliterated + "-" + str(uuid.uuid4())[:8])
        super(Survey, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Question(models.Model):
    TEXT = 'text'
    MULTIPLE_CHOICE = 'multiple_choice'
    SCALE = 'scale'

    QUESTION_TYPES = [
        (TEXT, 'Text'),
        (MULTIPLE_CHOICE, 'Multiple Choice'),
        (SCALE, 'Scale'),
    ]

    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    question_type = models.CharField(max_length=50, choices=QUESTION_TYPES)
    min_value = models.IntegerField(null=True, blank=True)
    max_value = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.text


class AnswerOption(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    option_text = models.CharField(max_length=255)

    def __str__(self):
        return self.option_text


class Response(models.Model):
    survey_question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.TextField()
    respondent_identifier = models.CharField(max_length=36)
    structured_data = models.JSONField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('survey_question', 'respondent_identifier')

    def __str__(self):
        return self.answer


class QuestionLogic(models.Model):
    question = models.ForeignKey(Question, related_name='current_question', on_delete=models.CASCADE)
    target_question = models.ForeignKey(Question, related_name='next_question', on_delete=models.CASCADE)
    trigger_answer = models.TextField()

    def __str__(self):
        return f"If {self.question.text} is '{self.trigger_answer}', go to {self.target_question.text}"

polls/forms.py
# surveys/forms.py

from django import forms
from django.forms import inlineformset_factory
from .models import Survey, Question, AnswerOption

# from snowpenguin.django.recaptcha3.fields import ReCaptchaField
#
#
# class SurveyForm(forms.Form):
#     captcha = ReCaptchaField()


class SurveyResponseForm(forms.Form):
    def __init__(self, *args, **kwargs):
        questions = kwargs.pop('questions')
        super().__init__(*args, **kwargs)
        for question in questions:
            field_name = f'question_{question.id}'
            if question.question_type == Question.TEXT:
                self.fields[field_name] = forms.CharField(label=question.text, required=True)
            elif question.question_type == Question.MULTIPLE_CHOICE:
                choices = [(option.option_text, option.option_text) for option in question.answeroption_set.all()]
                self.fields[field_name] = forms.ChoiceField(label=question.text, choices=choices,
                                                            widget=forms.RadioSelect, required=True)
            elif question.question_type == Question.SCALE:
                self.fields[field_name] = forms.IntegerField(
                    label=question.text,
                    widget=forms.NumberInput(attrs={'type': 'range',
                                                    'min': question.min_value,
                                                    'max': question.max_value}), required=True)
        # self.fields['captcha'] = ReCaptchaField()

polls/views.py
import base64
import os
from collections import Counter
from mimetypes import guess_type
from django.contrib import messages

from django.urls import reverse

from matplotlib import pyplot as plt
from django.http import HttpResponse, JsonResponse, Http404, HttpResponseRedirect
from django.views import View
from .utils import verify_recaptcha, validate_questions_data
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import io

from AnonPolls import settings
from common.views import TitleMixin
import json

from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import TemplateView, ListView, FormView
from django.db.models import Q

from .forms import SurveyResponseForm
from .models import Survey, Question, AnswerOption, Response, QuestionLogic
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import pandas as pd


class PollsPrivateListView(TitleMixin, ListView):
    model = Survey
    template_name = 'polls/private_polls.html'
    context_object_name = 'Survey'  # Use plural for context_object_name for clarity
    paginate_by = 6
    title = 'Мої опитування'

    def get_queryset(self):
        query = self.request.GET.get('q')
        user = self.request.user
        if query:
            return Survey.objects.filter(Q(title__icontains=query) & Q(author=user))
        return Survey.objects.filter(author=user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['authors'] = Survey.objects.filter(author=self.request.user)
        return context


class PollsListView(TitleMixin, ListView):
    model = Survey
    template_name = 'polls/polls.html'
    context_object_name = 'Survey'
    paginate_by = 6
    title = 'Публічні опитування'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Survey.objects.filter(Q(title__icontains=query))
        return Survey.objects.all()


class IndexView(TitleMixin, TemplateView):
    template_name = 'polls/index.html'
    title = 'SimpleAnonSurvey'


class CreateSurveyView(View):
    title = 'Створення опитувань'

    def get(self, request):
        return render(request, 'polls/create_polls.html', {'title': self.title,
                                                           'RECAPTCHA_PUBLIC_KEY': settings.RECAPTCHA_PUBLIC_KEY})

    def post(self, request):
        author = request.user
        title = request.POST.get('title')
        description = request.POST.get('description')
        show_author = request.POST.get('show_author') == 'true'
        survey_visibility = request.POST.get('survey_visibility')
        recaptcha_token = request.POST.get('recaptcha_token')

        errors = []

        # Verify reCAPTCHA
        if not verify_recaptcha(recaptcha_token):
            errors.append('Invalid reCAPTCHA. Please try again.')

        if not title:
            errors.append('Необхідно вказати назву.')
        if not survey_visibility:
            errors.append('Потрібна видимість огляду.')

        if errors:
            return render(request,
                          'polls/create_polls.html',
                          {'errors': errors, 'title': self.title,
                           'RECAPTCHA_PUBLIC_KEY': settings.RECAPTCHA_PUBLIC_KEY})

        survey = Survey(title=title,
                        description=description,
                        author=author,
                        show_author=show_author,
                        survey_visibility=survey_visibility)

        data = request.POST.get('questions_data')
        if not data:
            errors.append('Дані питань відсутні.')
            return render(request, 'polls/create_polls.html',
                          {'errors': errors, 'title': self.title,
                           'RECAPTCHA_PUBLIC_KEY': settings.RECAPTCHA_PUBLIC_KEY})

        try:
            questions = json.loads(data)
        except json.JSONDecodeError:
            errors.append('Недійсний формат даних запитань.')
            return render(request,
                          'polls/create_polls.html',
                          {'errors': errors, 'title': self.title,
                           'RECAPTCHA_PUBLIC_KEY': settings.RECAPTCHA_PUBLIC_KEY})

        if not questions:
            errors.append('Потрібно принаймні одне запитання.')
            return render(request,
                          'polls/create_polls.html',
                          {'errors': errors, 'title': self.title,
                           'RECAPTCHA_PUBLIC_KEY': settings.RECAPTCHA_PUBLIC_KEY})

        survey.save()

        for q in questions:
            question_text = q['text']
            question_type = q['question_type']
            options = q.get('options', [])
            if question_type == 'scale':
                if not options or len(options) != 2:
                    errors.append('Шкала запитань повинна мати мінімальне та максимальне значення.')
                    return render(request,
                                  'polls/create_polls.html',
                                  {'errors': errors, 'title': self.title,
                                   'RECAPTCHA_PUBLIC_KEY': settings.RECAPTCHA_PUBLIC_KEY})

                try:
                    min_value, max_value = int(options[0]), int(options[1])
                except ValueError:
                    errors.append('Мінімальне та максимальне значення повинні бути числовими.')
                    return render(request,
                                  'polls/create_polls.html',
                                  {'errors': errors, 'title': self.title,
                                   'RECAPTCHA_PUBLIC_KEY': settings.RECAPTCHA_PUBLIC_KEY})

                if min_value < -10000 or max_value > 10000:
                    errors.append('Мінімальне та максимальне значення повинні бути в діапазоні від -10000 до 10000.')
                    return render(request,
                                  'polls/create_polls.html',
                                  {'errors': errors, 'title': self.title,
                                   'RECAPTCHA_PUBLIC_KEY': settings.RECAPTCHA_PUBLIC_KEY})

                question = Question(text=question_text, question_type=question_type, survey=survey, min_value=min_value,
                                    max_value=max_value)
            else:
                question = Question(text=question_text, question_type=question_type, survey=survey)
            question.save()

            if question_type == 'multiple_choice':
                if not options:
                    errors.append('Питання з декількома відповідями повинні мати принаймні один варіант.')
                    return render(request,
                                  'polls/create_polls.html',
                                  {'errors': errors, 'title': self.title,
                                   'RECAPTCHA_PUBLIC_KEY': settings.RECAPTCHA_PUBLIC_KEY})
                for option_text in options:
                    answer_option = AnswerOption(question=question, option_text=option_text)
                    answer_option.save()

        return redirect('polls:index')


class EditSurveyView(View):
    def get(self, request, survey_slug):
        survey = get_object_or_404(Survey, slug=survey_slug)
        title = 'Редагування'
        questions = Question.objects.filter(survey=survey)
        return render(request, 'polls/edit_survey.html', {
            'survey': survey,
            'questions': questions,
            'title': title,
            'RECAPTCHA_PUBLIC_KEY': settings.RECAPTCHA_PUBLIC_KEY
        })

    def post(self, request, survey_slug):
        survey = get_object_or_404(Survey, slug=survey_slug)
        recaptcha_token = request.POST.get('recaptcha_token')

        if not verify_recaptcha(recaptcha_token):
            return JsonResponse({"error": "Недійсний reCAPTCHA. Будь ласка спробуйте ще раз."}, status=400)

        survey.title = request.POST.get('title')
        survey.save()

        questions_data = request.POST.get('questions_data')
        try:
            questions = json.loads(questions_data)
        except json.JSONDecodeError:
            return JsonResponse({"error": "Недійсні дані JSON"}, status=400)

        is_valid, error_message = validate_questions_data(questions)
        if not is_valid:
            return JsonResponse({"error": error_message}, status=400)

        existing_questions = {q.id: q for q in Question.objects.filter(survey=survey)}
        processed_question_ids = set()

        for q in questions:
            question_text = q['text']
            question_type = q['question_type']
            question = None

            for existing_question in existing_questions.values():
                if existing_question.text == question_text and existing_question.question_type == question_type:
                    question = existing_question
                    processed_question_ids.add(question.id)
                    break

            if question:
                if question_type == 'scale':
                    min_value, max_value = q.get('options')
                    question.min_value = min_value
                    question.max_value = max_value
                question.save()
            else:
                if question_type == 'scale':
                    min_value, max_value = q.get('options')
                    question = Question(
                        text=question_text,
                        question_type=question_type,
                        survey=survey,
                        min_value=min_value,
                        max_value=max_value
                    )
                else:
                    question = Question(
                        text=question_text,
                        question_type=question_type,
                        survey=survey
                    )
                question.save()

polls/templates/polls/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    
    <link href="{% static 'vendor/img/users/incognito_10351366.png' %}" rel="icon">
    <link href="{% static 'vendor/css/base.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/css/cookies.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.net.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <style>

        body, html {
        height: 100%;
        overflow-x: hidden;
        width: 100%;
        margin: 0;

    }

    #vanta-bg {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: -1;
        overflow-x: hidden;
    }


    .content-container {
        position: relative;
        z-index: 1;
        overflow-x: hidden;
        overflow-y: auto;

    }</style>


    {% block css %}{% endblock %}

</head>

<body>
{% include 'polls/cookies_banner.html' %}
<script src="{% static 'vendor/js/cookies.js' %}"></script>

<div id="vanta-bg" style="position: absolute"></div>

<div class="content-container d-flex flex-column min-vh-100">

    <nav class="navbar navbar-expand-lg navbar-red navbar-dark">
        <div class="wrapper"></div>
        <div class="container-fluid all-show">
            <a class="navbar-brand neon-text" href="{% url 'index' %}">SimpleAnonSurvey<i class="fa fa-codepen"></i></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Головна</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:index' %}">Публічні опитування</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'polls:private' %}">Особисті опитування</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'polls:create_survey' %}">Створити опитування</a>
                        </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
{#                                <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Особистий кабінет</a>#}
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">Вихід</a>
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Вхід</a></li>
{#                        <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">Реєстрація</a></li>#}
                    {% endif %}
                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Адмін-панель</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>



    {% block content %}{% endblock %}

    {% block footer %}
        <footer class="footer mt-auto py-3 bg-dark text-white">
            <div class="container1">
                <span>&copy; 2024 SimpleAnonSurvey. All rights reserved.</span>
            </div>
        </footer>
    {% endblock %}

</div>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

<script>
    VANTA.NET({
        el: '#vanta-bg',
        mouseControls: false,
        touchControls: true,
        gyroControls: true,
        minHeight: 200.00,
        minWidth: 200.00,
        scale: 1.00,
        scaleMobile: 1.00,
        color: 0x3fff6c,
        backgroundColor: 0x0,
        points: 20.00,
        maxDistance: 25.00,
        spacing: 14.00
    })


    // Automatically hide alerts after 5 seconds
    setTimeout(function () {
        $('.alert').fadeOut('slow');
    }, 3000);

    // Hide alerts when close button is clicked
    $('.alert .close').click(function () {
        $(this).closest('.alert').fadeOut('slow');

    });

</script>



</body>
</html>

polls/templates/polls/cookies_banner.html
<div id="cookie-banner" style="display:none;">
    <div class="cookie-banner-content">
        <p>Ми використовуємо кукі для покращення вашого досвіду на нашому сайті. 
            Продовжуючи користуватися нашим сайтом, ви погоджуєтесь з нашою політикою використання кукі.</p>
        <button id="accept-cookies">Прийняти</button>
    </div>
</div>

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% load static %}

{% block css %}
    {#<link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">#}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Toastr JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
{% endblock %}

{% block content %}
    <main>
        <div class="container col-lg-7 text-center mb-5 mt-5 ">
            <div class="jumbotron text-center mt-5">
                <h1 class="display-4">Вітаємо на сайті анонімних опитувань!</h1>
                <p class="lead">Тут ви можете переглянути доступні опитування та взяти участь у них.</p>
                <a class="btn btn-secondary btn-lg mb-2" href="{% url 'polls:index' %}" role="button">
                    Перегляд існуючих опитувань
                </a>
                <hr class="my-4">
                <p>Опитування – це потужний інструмент, який дозволяє зібрати важливу інформацію та думки.
                    Ми цінуємо вашу анонімність та гарантуємо, що всі відповіді залишатимуться конфіденційними.
                    Беріть участь в опитуваннях,
                    щоб допомогти нам зрозуміти ваші потреби та зробити наші сервіси кращими!</p>
                <p>Ваші відповіді допоможуть нам вдосконалити послуги та зробити їх більш корисними для вас.</p>
                <hr class="my-4">
                {% if user.is_authenticated %}
                    <a class="btn btn-primary btn-lg mb-2" href="{% url 'polls:create_survey' %}" role="button">
                        Почати створювати опитування
                    </a>

                {% else %}
                    <p>Щоб почати створювати опитування ви маєте мати обліковий запис зі статусом  "адмін", 
                        будь ласка, авторизуйтесь.</p>
                    <a class="btn btn-primary btn-lg mb-2" href="{% url 'users:login' %}" role="button">
                        Вхід
                    </a>
{#                    <a class="btn btn-secondary btn-lg mb-2" href="{% url 'users:register' %}" role="button">#}
{#                        Реєстрація#}
{#                    </a>#}
                {% endif %}
            </div>
        </div>
    </main>


    <script>
        $(document).ready(function () {
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": true,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            };
            {% if messages %}
                {% for message in messages %}
                    toastr.{{ message.tags }}('{{ message }}');
                {% endfor %}
            {% endif %}

        });
    </script>
{% endblock %}

polls/templates/polls/survey_detail.html
{% extends 'polls/base.html' %}
{% load static %}

{% block css %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'vendor/css/detail_survey.css' %} ">
    
{% endblock %}
{% block content %}
<div class="container mb-5 mt-5 col-lg-6">
    <h1>{{ survey.title }}</h1>
    {% if survey.author == this_user %}
    <div class="mb-3 text">
        <div class="d-inline-block">
            <a href="{% url 'polls:survey_statistics' survey.slug %}" class="btn btn-success btn-not-author">
                <i class="fas fa-chart-bar"></i> Результати
            </a>
        </div>
        <div class="d-inline-block ">
            <a href="{% url 'polls:edit_survey' survey.slug %}" class="btn btn-warning btn-not-author">
                <i class="fas fa-edit"></i> Редагувати
            </a>
            <form method="POST" action="{% url 'polls:delete_survey' survey.slug %}" onsubmit="return confirmDelete()" style="display: inline-block;">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">
                    <i class="fas fa-trash-alt"></i> Видалити
                </button>
            </form>
        </div>
    </div>
    {% endif %}
    <ul>
        {% for question in questions %}
        <li>
            <p>{{ forloop.counter }}. {{ question.text }} ({{ question.get_question_type_display }})</p>
            {% if question.question_type == 'multiple_choice' %}
            <ul>
                {% for option in question.answeroption_set.all %}
                <li>{{ option.option_text }}</li>
                {% endfor %}
            </ul>
            {% elif question.question_type == 'scale' %}
            <div class="scale-container">
                <span>{{ question.min_value }}</span>
                <input type="range" min="{{ question.min_value }}" max="{{ question.max_value }}" value="{{ question.min_value }}" id="range_{{ question.id }}" oninput="updateRangeValue({{ question.id }})">
                <span>{{ question.max_value }}</span>
            </div>
            <div class="text-md-center">
                <output class="scale-value" id="range_value_{{ question.id }}">{{ question.min_value }}</output>
            </div>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% if survey.show_author %}
    <div class="text-md-center mb-1">
        <h2>Автор опитування: {{ survey.author }}</h2>
    </div>
    {% endif %}
    <div class="action-buttons">
        <div class="input-group mb-3">
            <input type="text" value="{{ domain_name }}{% url 'polls:respond_to_survey' survey.slug %}" id="survey-link-{{ forloop.counter }}" class="form-control" readonly>
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" onclick="copyToClipboard('survey-link-{{ forloop.counter }}')">Copy Link</button>
            </div>
        </div>
        {% if survey.survey_visibility == 'public' %}
            {% if survey.author != this_user %}
        <a href="{% url 'polls:respond_to_survey' survey.slug %}" class="btn btn-primary mb-3">Відповісти</a>
        
            {% endif %}
        {% endif %}
    </div>

    <div class="text-md-center">
        <a href="{% url 'polls:index' %}" class="btn btn-secondary">Повернутись до списку опитувань</a>
    </div>
</div>
<div id="notification" style="display: none; color: red;"></div>
   <script>

    function confirmDelete() {
        return confirm('Ви впевнені, що хочете видалити це опитування?');
    }

    function copyToClipboard(elementId) {
        var copyText = document.getElementById(elementId);
        copyText.select();
        copyText.setSelectionRange(0, 99999); // For mobile devices
        document.execCommand("copy");
    }

    function updateRangeValue(questionId) {
        var rangeInput = document.getElementById('range_' + questionId);
        var rangeValue = document.getElementById('range_value_' + questionId);
        rangeValue.textContent = rangeInput.value;
    }
</script>
    

{% endblock %}